### PR TITLE
Add Python 3.14, update PEPs URL

### PR DESCRIPTION
**Pull request by hugovk**
Python 3.14 release schedule: https://peps.python.org/pep-0745/

### CODE REVIEW

**Comment by hroncok** [comment]
Thanks.

**Comment by hugovk** [comment]
Hello, okay to merge this?

**Comment by hroncok** [comment]
Sorry about that, I assumed Tomáš will double check and merge but I forgot to check with him.

**Comment by hrnciar** [comment]
Apologies! I've entirely missed this PR. Thank you.

**Pull request merged**
